# @package _group_
debug: False
seed: 1
num_gpu: 2

save_root: 'experiments'
experiment: 'experiment'
description:

start_fold:
load_checkpoint:
start_epoch: 1
num_epochs: 200
batch_size: 2
num_workers: 0
use_scheduler: True
data_parallel: False
tensorboard: False
amp: False
gradient_accumulation_steps: 1
checkpoint_epochs: [1, 50, 100, 150, 200]
device: 'cuda:0'
input_features:
  - 'image'
  - 'speckled_var'
